{"trial_id": "0015", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "units", "default": null, "conditions": [], "min_value": 32, "max_value": 512, "step": 32, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}, {"class_name": "Int", "config": {"name": "units_1", "default": null, "conditions": [], "min_value": 32, "max_value": 512, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_2", "default": null, "conditions": [], "min_value": 32, "max_value": 512, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_3", "default": null, "conditions": [], "min_value": 32, "max_value": 512, "step": 32, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_4", "default": null, "conditions": [], "min_value": 32, "max_value": 512, "step": 32, "sampling": "linear"}}], "values": {"units": 32, "learning_rate": 0.01, "tuner/epochs": 4, "tuner/initial_epoch": 2, "tuner/bracket": 2, "tuner/round": 1, "tuner/trial_id": "0011", "units_1": 32, "units_2": 32, "units_3": 32, "units_4": 32}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"C:\\Users\\pierg\\Documents\\Github\\Hands-On-Machine-Learning\\handsOnMachineLearning_venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"C:\\Users\\pierg\\Documents\\Github\\Hands-On-Machine-Learning\\handsOnMachineLearning_venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pierg\\Documents\\Github\\Hands-On-Machine-Learning\\handsOnMachineLearning_venv\\Lib\\site-packages\\keras_tuner\\src\\tuners\\hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pierg\\Documents\\Github\\Hands-On-Machine-Learning\\handsOnMachineLearning_venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pierg\\Documents\\Github\\Hands-On-Machine-Learning\\handsOnMachineLearning_venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pierg\\Documents\\Github\\Hands-On-Machine-Learning\\handsOnMachineLearning_venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pierg\\Documents\\Github\\Hands-On-Machine-Learning\\handsOnMachineLearning_venv\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"C:\\Users\\pierg\\Documents\\Github\\Hands-On-Machine-Learning\\handsOnMachineLearning_venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner_utils.py\", line 76, in on_epoch_end\n    self._save_model()\n  File \"C:\\Users\\pierg\\Documents\\Github\\Hands-On-Machine-Learning\\handsOnMachineLearning_venv\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner_utils.py\", line 86, in _save_model\n    self.model.save_weights(write_filepath)\n  File \"C:\\Users\\pierg\\Documents\\Github\\Hands-On-Machine-Learning\\handsOnMachineLearning_venv\\Lib\\site-packages\\h5py\\_hl\\files.py\", line 564, in __init__\n    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\pierg\\Documents\\Github\\Hands-On-Machine-Learning\\handsOnMachineLearning_venv\\Lib\\site-packages\\h5py\\_hl\\files.py\", line 244, in make_fid\n    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"h5py\\\\_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper\n  File \"h5py\\\\_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper\n  File \"h5py\\\\h5f.pyx\", line 122, in h5py.h5f.create\nOSError: Unable to synchronously create file (unable to truncate a file which is already open)\n"}